name: mychat
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - altair==5.0.1
    - annotated-types==0.5.0
    - anyio==3.7.1
    - appnope==0.1.3
    - asttokens==2.2.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - blinker==1.6.2
    - cachetools==5.3.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - comm==0.1.4
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - dnspython==2.4.2
    - executing==1.2.0
    - frozenlist==1.4.0
    - gitdb==4.0.10
    - gitpython==3.1.32
    - grpcio==1.57.0
    - grpcio-tools==1.57.0
    - h11==0.14.0
    - h2==4.1.0
    - hpack==4.0.0
    - httpcore==0.17.3
    - httpx==0.24.1
    - hyperframe==6.0.1
    - idna==3.4
    - importlib-metadata==6.8.0
    - ipykernel==6.25.1
    - ipython==8.14.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.3.0
    - jupyter-core==5.3.1
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - multidict==6.0.4
    - nest-asyncio==1.5.7
    - numpy==1.25.2
    - openai==0.27.9
    - packaging==23.1
    - pandas==2.0.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.10.0
    - portalocker==2.7.0
    - prompt-toolkit==3.0.39
    - protobuf==4.24.2
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==13.0.0
    - pydantic==2.3.0
    - pydantic-core==2.6.3
    - pydeck==0.8.0
    - pygments==2.16.1
    - pymongo==4.5.0
    - pympler==1.0.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyzmq==25.1.1
    - qdrant-client==1.4.0
    - referencing==0.30.2
    - requests==2.31.0
    - rich==13.5.2
    - rpds-py==0.9.2
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - stack-data==0.6.2
    - streamlit==1.26.0
    - tenacity==8.2.3
    - toml==0.10.2
    - toolz==0.12.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.9.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - tzlocal==4.3.1
    - urllib3==1.26.16
    - validators==0.21.2
    - wcwidth==0.2.6
    - xpyutils==0.0.4
    - yarl==1.9.2
    - zipp==3.16.2
